### PR TITLE
cdc codes with local build and local unit test

### PR DESCRIPTION
**Pull request by zeminzhou**
Modified cdc codes that can make by Makefile.

### CODE REVIEW

**Comment by zeminzhou** [comment]
@pingyu

**Comment by zeminzhou** [comment]
> @pingyu
PTAL~

**Comment by pingyu** [comment]
The `Makefile` in root directory seems to be duplicated. Rest LGTM~

**Comment by pingyu** [comment]
One more thing, codes import last time should be removed, or moved to `migration/cdc/cdc`.

**Comment by zeminzhou** [comment]
> One more thing, codes import last time should be removed, or moved to `migration/cdc/cdc`.

I created a new pr for removing old cdc codes

**Comment by pingyu** [comment]
> > One more thing, codes import last time should be removed, or moved to `migration/cdc/cdc`.
> 
> I created a new pr for removing old cdc codes

OK.

**Review by pingyu — APPROVED** [review]
LGTM.

**Pull request merged**
