### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

The minimum TiUP version has been released

### Code changes

- No code

### Check List for Tests

- No code

### Side effects

- No side effects

### Related changes

- No related changes

### CODE REVIEW

**Comment by pingyu** [comment]
Hi @dveeden , please sign off the commit, thanks.

**Comment by dveeden** [comment]
> Hi @dveeden , please sign off the commit, thanks.

done

**Review by pingyu — APPROVED** [review]
LGTM, thanks for your contribution !

**Review by haojinming — APPROVED** [review]
LGTM

**Pull request merged**
