### PR TITLE
[close #333] update client-go version to fix context leak

### LINKED ISSUE #333: cdc: Memory leak
### 1. Describe the bug

Customers report that memory usage of TiKV-CDC keep increasing along with time. (For information safety, the metrics & snapshot cannot be provided here).

### 2. Minimal reproduce step (Required)

See https://github.com/tikv/client-go/issues/696.

### 5. What is your migration tool and TiKV version? (Required)

- TiKV: v6.2.0
- TiKV CDC: v1.1.0-master, 00d7fc8aafd4d474430b836dd72c5126449be412
- TiKV BR:
- TiKV Online Bulk Load:

### PR DESCRIPTION
**Pull request by pingyu**
Signed-off-by: Ping Yu <yuping@pingcap.com>

### What problem does this PR solve?

Issue Number: close #333 

Problem Description: Memory leak

### What is changed and how does it work?

Update `client-go` version which has fixed this issue.
See https://github.com/tikv/client-go/pull/697

### Changes on [`client-go`](https://github.com/pingyu/client-go/tree/tikv-cdc)
PR: https://github.com/pingyu/client-go/pull/1
Diff: https://github.com/pingyu/client-go/compare/6ec40fff4e31..74fe33153943
Cherry-pick:
- https://github.com/tikv/client-go/pull/612
- https://github.com/tikv/client-go/pull/673
- https://github.com/tikv/client-go/pull/697

### Code changes

- No code

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Unit test
- Integration test
- No code

### Side effects

- No side effects

### Related changes

- No related changes

### To reviewers

Please follow these principles to check this pull requests:

- **Concentration**. One pull request should only do one thing. No matter how small it is, the change does exactly one thing and gets it right. Don't mix other changes into it.
- **Tests**. A pull request should be test covered, whether the tests are unit tests, integration tests, or end-to-end tests. Tests should be sufficient, correct and don't slow down the CI pipeline largely.
- **Functionality**. The pull request should implement what the author intends to do and fit well in the existing code base, resolve a real problem for TiDB/TiKV users. To get the author's intention and the pull request design, you could follow the discussions in the corresponding GitHub issue or [internal.tidb.io](https://internals.tidb.io) topic.
- **Style**. Code in the pull request should follow common programming style. *(For Go, we have style checkers in CI)*. However, sometimes the existing code is inconsistent with the style guide, you should maintain consistency with the existing code or file a new issue to fix the existing code style first.
- **Documentation**. If a pull request changes how users build, test, interact with, or release code, you must check whether it also updates the related documentation such as READMEs and any generated reference docs. Similarly, if a pull request deletes or deprecates code, you must check whether or not the corresponding documentation should also be deleted.
- **Performance**. If you find the pull request may affect performance, you could ask the author to provide a benchmark result.

*(The above text mainly refers to [TiDB Development Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/review-a-pr.html#checking-pull-requests). It's also highly recommended to read about [Writing code review comments](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/review-a-pr.html#writing-code-review-comments))*

### CODE REVIEW

**Review by haojinming — APPROVED** [review]
LGTM

**Review by zeminzhou — APPROVED** [review]
LGTM~

**Pull request merged**
