### PR TITLE
[fix #278] fix metric `Sink write rows count/s` show wrong name

### LINKED ISSUE #278: cdc: metric `Sink write rows count/s` show wrong name
### 1. Describe the bug

metric `Sink write rows count/s` show wrong name
image

### 2. Minimal reproduce step (Required)
1. start up clusters
2. creat multi changefeeds
3. input data into upstream cluster

### 3. What did you see instead (Required)
show `total` in  `Sink write rows count/s` 

### 4. What did you expect to see? (Required)
show changefeed name in  `Sink write rows count/s`

### PR DESCRIPTION
**Pull request by zeminzhou**
Signed-off-by: zeminzhou <zhouzemin@pingcap.com>

### What problem does this PR solve?
fix metric `Sink write rows count/s` show wrong name

Issue Number: close #278

Problem Description: **TBD**

### What is changed and how does it work?
`total` -> `{{changefeed}}`

### Code changes

- No code

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Manual test (add detailed scripts or steps below)

### Side effects

- No side effects

### Related changes

- No related changes

### CODE REVIEW

**Comment by zeminzhou** [comment]
PTAL~ /cc @pingyu @haojinming

**Review by haojinming — APPROVED** [review]
Please help to paste the grafana view. REST LGTM

**Comment by zeminzhou** [comment]
image

**Review by pingyu — APPROVED** [review]
LGTM~

**Pull request merged**
