### PR TITLE
[close #300] remove unused code & remove modified it cases

### LINKED ISSUE #300: cdc: remove unused codes
## Feature Request

**Is your feature request related to a problem? Please describe:**

1. `example` in `migration/cdc` maybe is useless for TiKV-CDC
2. some test cases in `.unmodified` has modified for TiKV-CDC, we should remove them.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

### PR DESCRIPTION
**Pull request by zeminzhou**
Signed-off-by: zeminzhou <zhouzemin@pingcap.com>

### What problem does this PR solve?

Issue Number: close #300

Problem Description: **TBD**

### What is changed and how does it work?
remove useless code for TiKV-CDC

### Code changes

- No code

### Check List for Tests

This PR has been tested by at least one of the following methods:
- No code

### Side effects

- No side effects

### Related changes

- No related changes

### CODE REVIEW

**Comment by zeminzhou** [comment]
@PTAL~

**Review by haojinming — APPROVED** [review]
LGTM

**Review by pingyu — APPROVED** [review]
LGTM~

**Pull request merged**
