### PR TITLE
[fix #271] remove cdc usedless panel show on metric

### LINKED ISSUE #271: cdc: A lot of useless panel show on metric
### 1. Describe the bug

A lot of useless panel show on metric, as follow:
image

image

And we should remove them.

### 2. Minimal reproduce step (Required)
1. start up tikv & tikv-cdc
2. open metric

### 3. What did you see instead (Required)
A lot of useless panel show on metric.

### 4. What did you expect to see? (Required)
All panel should be useful.

### 5. What is your migration tool and TiKV version? (Required)

- TiKV: v6.3.0
- TiKV CDC: main branch

### PR DESCRIPTION
**Pull request by zeminzhou**
Signed-off-by: zeminzhou <zhouzemin@pingcap.com>

### What problem does this PR solve?

Issue Number: close #271
remove cdc usedless panel show on metric

Problem Description: **TBD**
see issue#271

### What is changed and how does it work?
remove them
image
image

### Code changes

- No code

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Manual test (add detailed scripts or steps below)

### Side effects

- No side effects

### CODE REVIEW

**Comment by zeminzhou** [comment]
@PTAL~

**Comment by zeminzhou** [comment]
changefeed
image
image
image

**Comment by zeminzhou** [comment]
dataflow
image
image

**Comment by zeminzhou** [comment]
event
image
image
image

**Comment by zeminzhou** [comment]
unified sorter
image

**Comment by zeminzhou** [comment]
tikv
image
image

**Comment by zeminzhou** [comment]
runtime
image

**Comment by zeminzhou** [comment]
tikv sink
image

**Review by pingyu — APPROVED** [review]
Great ! LGTM~

**Review by haojinming — APPROVED** [review]

**Pull request merged**
